-- Profiles table
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  avatar_url TEXT,
  is_admin BOOLEAN DEFAULT FALSE,
  first_name TEXT,
  middle_name TEXT,
  surname TEXT,
  date_of_birth DATE,
  gender TEXT,
  old_id INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Letters table
CREATE TABLE public.letters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  nickname TEXT,
  name TEXT NOT NULL,
  to_country TEXT NOT NULL,
  from_country TEXT NOT NULL DEFAULT 'Qatar',
  sent_date DATE,
  received_date DATE,
  days INTEGER,
  tracking TEXT,
  letter_type TEXT CHECK (letter_type IN ('Sending', 'Receiving')) NOT NULL,
  direction TEXT CHECK (direction IN ('sending', 'receiving')),
  to_city TEXT,
  from_city TEXT,
  to_zip_code TEXT,
  from_zip_code TEXT,
  to_address_line1 TEXT,
  to_address_line2 TEXT,
  from_address_line1 TEXT,
  from_address_line2 TEXT,
  is_completed BOOLEAN DEFAULT FALSE,
  status TEXT DEFAULT 'Active',
  attachment_url TEXT,
  old_user_id INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS (Row Level Security) Policies
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.letters ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own profile" ON public.profiles
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can view their own letters" ON public.letters
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own letters" ON public.letters
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own letters" ON public.letters
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own letters" ON public.letters
  FOR DELETE USING (auth.uid() = user_id);

-- Admin policies
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN (
    SELECT is_admin 
    FROM public.profiles 
    WHERE id = auth.uid()
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE POLICY "Admins can view all profiles" ON public.profiles
  FOR SELECT USING (auth.uid() = id OR public.is_admin());

CREATE POLICY "Admins can view all letters" ON public.letters
  FOR SELECT USING (auth.uid() = user_id OR public.is_admin());

-- The admin panel (src/app/admin/page.tsx) updates/deletes any user's
-- profile and deletes any user's letters. Those actions need explicit
-- admin write policies, since the "own row" policies above don't cover them.
DROP POLICY IF EXISTS "Admins can update all profiles" ON public.profiles;
CREATE POLICY "Admins can update all profiles" ON public.profiles
  FOR UPDATE USING (public.is_admin());

DROP POLICY IF EXISTS "Admins can delete profiles" ON public.profiles;
CREATE POLICY "Admins can delete profiles" ON public.profiles
  FOR DELETE USING (public.is_admin());

DROP POLICY IF EXISTS "Admins can delete letters" ON public.letters;
CREATE POLICY "Admins can delete letters" ON public.letters
  FOR DELETE USING (public.is_admin());

-- Site settings (logo, favicon, footer text) shown to all visitors via
-- src/app/layout.tsx and src/components/layout/Navbar.tsx, and edited from
-- the admin panel. This table existed in the live project but was missing
-- from this schema file.
CREATE TABLE IF NOT EXISTS public.settings (
  id TEXT PRIMARY KEY DEFAULT 'global',
  logo_url TEXT,
  favicon_url TEXT,
  title TEXT,
  description TEXT,
  footer_text TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view settings" ON public.settings;
CREATE POLICY "Anyone can view settings" ON public.settings
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins can update settings" ON public.settings;
CREATE POLICY "Admins can update settings" ON public.settings
  FOR UPDATE USING (public.is_admin());

DROP POLICY IF EXISTS "Admins can insert settings" ON public.settings;
CREATE POLICY "Admins can insert settings" ON public.settings
  FOR INSERT WITH CHECK (public.is_admin());

INSERT INTO public.settings (id) VALUES ('global')
  ON CONFLICT (id) DO NOTHING;

-- Function to handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
